# Generated by Django 3.0.8 on 2020-08-03 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_reportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='added_by_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('school', 'for_date', 'added_by_school')},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('item', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.District')),
            ],
            options={
                'unique_together': {('district', 'day', 'item')},
            },
        ),
        migrations.CreateModel(
            name='AuthorityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='api.Report')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='api.Report')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'unique_together': {('school', 'for_date')},
            },
        ),
    ]
